from fastapi import APIRouter, HTTPException
from ..services.supabase_client import get_supabase

router = APIRouter()

@router.get("/")
async def list_alerts():
    return {"alerts": [], "message": "Alerts are generated in real-time by the AI engine"}

@router.get("/recommendations")
async def list_recommendations():
    return {"recommendations": [], "message": "Recommendations are generated by the AI prediction engine"}
