/*
# Predictive Maintenance System - Complete Schema

## Overview
Full schema for an AI-powered industrial predictive maintenance system.
Users can monitor multiple machines with multiple sensors, receive AI-generated
alerts, view predictions, and track maintenance history.

## Tables Created

### 1. machines
Stores the factory machines being monitored.
- id: UUID primary key
- user_id: Owner (defaults to auth.uid())
- name: Machine display name (e.g., "Compressor Unit 01")
- location: Physical location string
- status: 'online' | 'offline' | 'warning' | 'critical'
- description: Optional notes
- rms_min / rms_max: Vibration RMS thresholds (g)
- temp_min / temp_max: Temperature thresholds (°C)
- current_min / current_max: Current thresholds (A)
- created_at, updated_at

### 2. sensor_snapshots
Periodic (5s) averaged readings per machine. Used for trends.
- id: UUID primary key
- machine_id: FK to machines
- user_id: Owner
- temperature: °C
- vibration_rms: g (combined X/Y RMS)
- current: A
- rpm: revolutions per minute
- voltage: V
- recorded_at: timestamptz

### 3. alerts
Machine-level alerts and warnings generated by AI detection.
- id: UUID primary key
- machine_id: FK to machines
- user_id: Owner
- type: 'bearing_wear' | 'overheating' | 'abnormal_vibration' | 'current_spike' | 'rpm_anomaly'
- severity: 'info' | 'warning' | 'critical'
- message: Human-readable description
- is_read: Whether user has acknowledged
- resolved_at: When resolved (nullable)
- created_at

### 4. predictions
AI health assessment snapshots per machine.
- id: UUID primary key
- machine_id: FK to machines
- user_id: Owner
- health_score: 0-100 overall health percentage
- status: 'healthy' | 'warning' | 'critical'
- bearing_wear_pct: 0-100
- overheating_risk_pct: 0-100
- failure_risk_pct: 0-100
- rul_hours: Remaining Useful Life estimate in hours
- predicted_at

### 5. maintenance_logs
History of maintenance actions performed on machines.
- id: UUID primary key
- machine_id: FK to machines
- user_id: Owner
- action: Short action title
- notes: Detailed notes
- performed_by: Name/role of technician
- performed_at

### 6. machine_health
Latest health snapshot per machine (upserted on update).
- machine_id: PK (one row per machine)
- user_id: Owner
- rms_x, rms_y: Per-axis RMS (g)
- temperature: °C
- current: A
- rpm: RPM
- voltage: V
- health_score: 0-100
- status: health status string
- updated_at

## Security
- RLS enabled on all tables
- All policies scoped to authenticated users
- Each user can only access their own data (user_id = auth.uid())
- Separate policies for SELECT / INSERT / UPDATE / DELETE
*/

-- ============================================================
-- MACHINES
-- ============================================================
CREATE TABLE IF NOT EXISTS machines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  location text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'online' CHECK (status IN ('online','offline','warning','critical')),
  rms_min numeric NOT NULL DEFAULT 0.5,
  rms_max numeric NOT NULL DEFAULT 3.0,
  temp_min numeric NOT NULL DEFAULT 20.0,
  temp_max numeric NOT NULL DEFAULT 85.0,
  current_min numeric NOT NULL DEFAULT 0.5,
  current_max numeric NOT NULL DEFAULT 5.0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE machines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "machines_select" ON machines;
CREATE POLICY "machines_select" ON machines FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "machines_insert" ON machines;
CREATE POLICY "machines_insert" ON machines FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "machines_update" ON machines;
CREATE POLICY "machines_update" ON machines FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "machines_delete" ON machines;
CREATE POLICY "machines_delete" ON machines FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- SENSOR SNAPSHOTS
-- ============================================================
CREATE TABLE IF NOT EXISTS sensor_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  machine_id uuid NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  temperature numeric NOT NULL DEFAULT 0,
  vibration_rms numeric NOT NULL DEFAULT 0,
  current numeric NOT NULL DEFAULT 0,
  rpm integer NOT NULL DEFAULT 0,
  voltage numeric NOT NULL DEFAULT 0,
  recorded_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sensor_snapshots_machine_time ON sensor_snapshots(machine_id, recorded_at DESC);

ALTER TABLE sensor_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "snapshots_select" ON sensor_snapshots;
CREATE POLICY "snapshots_select" ON sensor_snapshots FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "snapshots_insert" ON sensor_snapshots;
CREATE POLICY "snapshots_insert" ON sensor_snapshots FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "snapshots_update" ON sensor_snapshots;
CREATE POLICY "snapshots_update" ON sensor_snapshots FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "snapshots_delete" ON sensor_snapshots;
CREATE POLICY "snapshots_delete" ON sensor_snapshots FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- ALERTS
-- ============================================================
CREATE TABLE IF NOT EXISTS alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  machine_id uuid NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('bearing_wear','overheating','abnormal_vibration','current_spike','rpm_anomaly')),
  severity text NOT NULL DEFAULT 'warning' CHECK (severity IN ('info','warning','critical')),
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  resolved_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS alerts_machine_created ON alerts(machine_id, created_at DESC);
CREATE INDEX IF NOT EXISTS alerts_user_unread ON alerts(user_id, is_read, created_at DESC);

ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "alerts_select" ON alerts;
CREATE POLICY "alerts_select" ON alerts FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "alerts_insert" ON alerts;
CREATE POLICY "alerts_insert" ON alerts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "alerts_update" ON alerts;
CREATE POLICY "alerts_update" ON alerts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "alerts_delete" ON alerts;
CREATE POLICY "alerts_delete" ON alerts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- PREDICTIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS predictions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  machine_id uuid NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  health_score numeric NOT NULL DEFAULT 100 CHECK (health_score BETWEEN 0 AND 100),
  status text NOT NULL DEFAULT 'healthy' CHECK (status IN ('healthy','warning','critical')),
  bearing_wear_pct numeric NOT NULL DEFAULT 0,
  overheating_risk_pct numeric NOT NULL DEFAULT 0,
  failure_risk_pct numeric NOT NULL DEFAULT 0,
  rul_hours integer NOT NULL DEFAULT 9999,
  predicted_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS predictions_machine_time ON predictions(machine_id, predicted_at DESC);

ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "predictions_select" ON predictions;
CREATE POLICY "predictions_select" ON predictions FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "predictions_insert" ON predictions;
CREATE POLICY "predictions_insert" ON predictions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "predictions_update" ON predictions;
CREATE POLICY "predictions_update" ON predictions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "predictions_delete" ON predictions;
CREATE POLICY "predictions_delete" ON predictions FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- MAINTENANCE LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS maintenance_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  machine_id uuid NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  action text NOT NULL,
  notes text NOT NULL DEFAULT '',
  performed_by text NOT NULL DEFAULT 'System',
  performed_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS maint_logs_machine_time ON maintenance_logs(machine_id, performed_at DESC);

ALTER TABLE maintenance_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "maint_select" ON maintenance_logs;
CREATE POLICY "maint_select" ON maintenance_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "maint_insert" ON maintenance_logs;
CREATE POLICY "maint_insert" ON maintenance_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "maint_update" ON maintenance_logs;
CREATE POLICY "maint_update" ON maintenance_logs FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "maint_delete" ON maintenance_logs;
CREATE POLICY "maint_delete" ON maintenance_logs FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ============================================================
-- MACHINE HEALTH (latest snapshot per machine)
-- ============================================================
CREATE TABLE IF NOT EXISTS machine_health (
  machine_id uuid PRIMARY KEY REFERENCES machines(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rms_x numeric NOT NULL DEFAULT 0,
  rms_y numeric NOT NULL DEFAULT 0,
  temperature numeric NOT NULL DEFAULT 0,
  current numeric NOT NULL DEFAULT 0,
  rpm integer NOT NULL DEFAULT 0,
  voltage numeric NOT NULL DEFAULT 0,
  health_score numeric NOT NULL DEFAULT 100,
  status text NOT NULL DEFAULT 'healthy',
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE machine_health ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "health_select" ON machine_health;
CREATE POLICY "health_select" ON machine_health FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "health_insert" ON machine_health;
CREATE POLICY "health_insert" ON machine_health FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "health_update" ON machine_health;
CREATE POLICY "health_update" ON machine_health FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "health_delete" ON machine_health;
CREATE POLICY "health_delete" ON machine_health FOR DELETE TO authenticated USING (auth.uid() = user_id);
